apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-group-manager-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az-group-manager-controller
  template:
    metadata:
      labels:
        app: az-group-manager-controller
    spec:
      serviceAccountName: az-group-manager
      containers:
        - name: controller
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          args: ['serve']
          env:
            - name: AZ_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: az-group-manager
                  key: tenant-id
            - name: AZ_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: az-group-manager
                  key: client-id
            - name: AZ_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: az-group-manager
                  key: client-secret
            - name: STRUCTURED_LOGS
              value: {{ .Values.structuredLogs | quote }}
            - name: RECONCILE_TIME
              value: {{ .Values.reconcileTime | quote }}
            - name: RETRY_TIME
              value: {{ .Values.retryTime | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
      securityContext:
        seccompProfile:
          type: RuntimeDefault
